- hosts: all
  user: "root"
  vars:
          ansible_ssh_port: 22
          ansible_python_interpreter: "/usr/local/bin/python3.6"
          ansible_port: 22
  tasks:
    - name: Enable cuse support in /etc/rc.conf
      shell: |
        sysrc kld_list+=" cuse.ko"
 
    - name: Restart kld service to load cuse kernel module  
      service: name=kld state=restarted 
      ignore_errors: True

    - name: Install packages for webcam on FreeBSD
      pkgng:
          name: webcamd
          state: present
 
    - name: Add users to webcamd group
      shell: |
        grep -E 1[0-9]{3}  /etc/passwd | sed s/:/\ / | awk '{print $1}' | xargs pw groupmod webcamd -m

    - name: Enable active webcams
      shell: |
        sysrc webcamd_enable="YES"
        usbconfig | grep Cam | awk '{print $1}' | cut -d : -f 1 | xargs service webcamd restart
        usbconfig | grep Vid | awk '{print $1}' | cut -d : -f 1 | xargs service webcamd restart

    - name: Enable and start all services for webcam on FreeBSD
      service:
          name: "{{ item }}"
          enabled: true
          state: started
      with_items:
         - webcamd 
