- hosts: all
  user: "root"
  vars:
          ansible_ssh_port: 22
          ansible_python_interpreter: "/usr/local/bin/python3.6"
          ansible_port: 22
  tasks:
    - name: Install packages for intel GPU on FreeBSD
      pkgng:
          name: drm-kmod 
          state: present
 
    - name: Enable drm-kmod support in /etc/rc.conf
      shell: |
        sysrc kld_list+=" /boot/modules/i915kms.ko"
 
    - name: Restart kld service to load i915kms kernel module  
      service: name=kld state=restarted
      ignore_errors: True

    - name: Add users to video group
      shell: |
        grep -E 1[0-9]{3}  /etc/passwd | sed s/:/\ / | awk '{print $1}' | xargs pw groupmod video -m
