- hosts: all
  user: "root"
  vars:
          ansible_ssh_port: 22
          ansible_python_interpreter: "/usr/local/bin/python3.6"
          ansible_port: 22
  tasks:
     - name: Install packages for plasma on FreeBSD
      pkgng:
          name: xorg, kde5, sddm
          state: present
 
    - name: Enable and start all services for Plamsa FreeBSD
      service:
          name: "{{ item }}"
          enabled: true
          state: started
      with_items:
         - dbus
         - sddm
