- hosts: all
  user: "root"
  vars:
          ansible_ssh_port: 22
          ansible_python_interpreter: "/usr/local/bin/python3.6"
          ansible_port: 22
  tasks:
    - name: Install apps on FreeBSD
      pkgng:
          name: firefox, thunderbird, libreoffice
          state: present
