- hosts: all
  user: "root"
  vars:
          ansible_ssh_port: 22
          ansible_python_interpreter: "/usr/local/bin/python3.6"
          ansible_port: 22
  tasks:
    - name: Install packages for hald on FreeBSD
      pkgng:
          name: hal 
          state: present

    - name: Enable and start all services for avahi on FreeBSD
      service:
          name: "{{ item }}"
          enabled: true
          state: started
      with_items:
         - hald 
